title: The amiibo Source
description: A website dedicated to fast and accurate information regarding all aspects of Super Smash Bros. Ultimate amiibo.
theme: just-the-docs

url: https://amiibo-guides.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
