title: The amiibo Source
description: A website dedicated to fast and accurate information regarding all aspects of Super Smash Bros. Ultimate amiibo.
theme: just-the-docs

url: https://amiibo-guides.github.io

nav_external_links:
  - title: "Join our Discord Server"
    url: "https://discord.gg/xtPUVKTPGe"
    hide_icon: false
